<?php

declare(strict_types=1);

/*   This script is for de-identifying an OpenEMR database for the purpose of creating a live demo or for
    development using real data but keepinng patient identities a secret.  The script does the following

        * removing patient information from the patient_data table and replacing patient demographics with a randomly generated name
        * replacing data stored in the the insurance_data table with the random generated name
        * specfying insurance subscriber as self and populating the subscriber info with auto-generated data from step 1.
        * clearing provider and staff information in the user table replacing it with autogenerated and unique names and IDN's
        * truncating the log tables since personal information may be stored there
        * removes data in forms - END USER MUST EDIT deIdForms function to enure all form data is removed.

    There is no turnging back.......

    To use:

    1) Enter values for host, user, database, password
    2) type: php deidentification_OpenEMR.php

    Your database now has deidientified all data and can never be restored.

 * Copyright (C) 2017 Daniel Pflieger <growlingflea@gmail.com daniel@mi-squared.com and OEMR <www.oemr.org>
 *
 * LICENSE: This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://opensource.org/licenses/gpl-license.php>;.
 *
 * @package OpenEMR
 * @author  Daniel Pflieger <growlingflea@gmail.com> <daniel@mi-squared.com>
 * @link    http://www.open-emr.org


    NOTE:  IT IS STILL THE RESPONSIBILITY OF THE USER TO ENSURE THAT ALL PERSONAL IDENTIFIABLE INFORMATION HAS BEEN DELETED FROM THE DATABASE.  THE END USER
    MUST MAKE SURE THAT ALL TEXT AREAS IN FORMS DO NOT INCLUDE THE PATIENTS REAL NAME.
*/


//Contact the database
//$con = mysqli_connect("HOST","USER","PASS","DATABASE") or die("Some error occurred during connection " . mysqli_error($con));

//Instructions:  Change these 4 values.  The run as a normal php script
//Remember - there is no turning back

//To run script, comment out the return line, fill out the databae credentials, and run.  Uncomment out the return statement when complete.
return 0;
