<?php

/**
 * DateHelper tests to verify Carbon integration
 *
 * @package   OpenEMR
 * @link      http://www.open-emr.org
 * @author    GitHub Copilot AI Assistant
 * @copyright Copyright (c) 2025 OpenEMR
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

namespace OpenEMR\Tests\Unit\Common\Utils;

// Generated by GitHub Copilot
use OpenEMR\Common\Utils\DateHelper;
use PHPUnit\Framework\TestCase;
use Carbon\Carbon;

class DateHelperTest extends TestCase
{
    public function testParseReturnsCurrentDateWhenNull(): void
    {
        $result = DateHelper::parse(null);
        $this->assertInstanceOf(Carbon::class, $result);
        $this->assertEquals(Carbon::now()->format('Y-m-d'), $result->format('Y-m-d'));
    }

    public function testParseHandlesTimestamp(): void
    {
        $timestamp = strtotime('2025-01-15 10:30:00');
        $result = DateHelper::parse($timestamp);
        $this->assertInstanceOf(Carbon::class, $result);
        $this->assertEquals('2025-01-15', $result->format('Y-m-d'));
    }

    public function testParseHandlesDateString(): void
    {
        $result = DateHelper::parse('2025-01-15');
        $this->assertInstanceOf(Carbon::class, $result);
        $this->assertEquals('2025-01-15', $result->format('Y-m-d'));
    }

    public function testFormatToSqlDate(): void
    {
        $result = DateHelper::formatToSqlDate('2025-01-15 14:30:00');
        $this->assertEquals('2025-01-15', $result);
    }

    public function testFormatToSqlDateTime(): void
    {
        $result = DateHelper::formatToSqlDateTime('2025-01-15 14:30:00');
        $this->assertMatchesRegularExpression('/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/', $result);
    }

    public function testAddDays(): void
    {
        $result = DateHelper::addDays('2025-01-15', 5);
        $this->assertEquals('2025-01-20', $result->format('Y-m-d'));
    }

    public function testAddDaysNegative(): void
    {
        $result = DateHelper::addDays('2025-01-15', -5);
        $this->assertEquals('2025-01-10', $result->format('Y-m-d'));
    }

    public function testAddWeeks(): void
    {
        $result = DateHelper::addWeeks('2025-01-15', 2);
        $this->assertEquals('2025-01-29', $result->format('Y-m-d'));
    }

    public function testAddMonths(): void
    {
        $result = DateHelper::addMonths('2025-01-15', 3);
        $this->assertEquals('2025-04-15', $result->format('Y-m-d'));
    }

    public function testSubDays(): void
    {
        $result = DateHelper::subDays('2025-01-15', 5);
        $this->assertEquals('2025-01-10', $result->format('Y-m-d'));
    }

    public function testSubWeeks(): void
    {
        $result = DateHelper::subWeeks('2025-01-15', 2);
        $this->assertEquals('2025-01-01', $result->format('Y-m-d'));
    }

    public function testSubMonths(): void
    {
        $result = DateHelper::subMonths('2025-01-15', 1);
        $this->assertEquals('2024-12-15', $result->format('Y-m-d'));
    }

    public function testDiffInDays(): void
    {
        $result = DateHelper::diffInDays('2025-01-15', '2025-01-20');
        $this->assertEquals(5, $result);
    }

    public function testDiffInDaysAbsolute(): void
    {
        $result = DateHelper::diffInDays('2025-01-20', '2025-01-15', true);
        $this->assertEquals(5, $result);
    }

    public function testDiffInHours(): void
    {
        $result = DateHelper::diffInHours('2025-01-15 10:00:00', '2025-01-15 15:00:00');
        $this->assertEquals(5, $result);
    }

    public function testIsPast(): void
    {
        $pastDate = Carbon::yesterday()->format('Y-m-d');
        $this->assertTrue(DateHelper::isPast($pastDate));
        
        $futureDate = Carbon::tomorrow()->format('Y-m-d');
        $this->assertFalse(DateHelper::isPast($futureDate));
    }

    public function testIsFuture(): void
    {
        $futureDate = Carbon::tomorrow()->format('Y-m-d');
        $this->assertTrue(DateHelper::isFuture($futureDate));
        
        $pastDate = Carbon::yesterday()->format('Y-m-d');
        $this->assertFalse(DateHelper::isFuture($pastDate));
    }

    public function testIsToday(): void
    {
        $today = Carbon::today()->format('Y-m-d');
        $this->assertTrue(DateHelper::isToday($today));
        
        $yesterday = Carbon::yesterday()->format('Y-m-d');
        $this->assertFalse(DateHelper::isToday($yesterday));
    }

    public function testToTimestamp(): void
    {
        $dateStr = '2025-01-15 10:30:00';
        $result = DateHelper::toTimestamp($dateStr);
        $this->assertIsInt($result);
        $this->assertEquals(strtotime($dateStr), $result);
    }

    public function testIsGreaterThan(): void
    {
        $this->assertTrue(DateHelper::isGreaterThan('2025-01-20', '2025-01-15'));
        $this->assertFalse(DateHelper::isGreaterThan('2025-01-15', '2025-01-20'));
    }

    public function testIsLessThan(): void
    {
        $this->assertTrue(DateHelper::isLessThan('2025-01-15', '2025-01-20'));
        $this->assertFalse(DateHelper::isLessThan('2025-01-20', '2025-01-15'));
    }

    public function testIsSameDay(): void
    {
        $this->assertTrue(DateHelper::isSameDay('2025-01-15 10:00:00', '2025-01-15 15:00:00'));
        $this->assertFalse(DateHelper::isSameDay('2025-01-15', '2025-01-16'));
    }

    public function testStartOfDay(): void
    {
        $result = DateHelper::startOfDay('2025-01-15 15:30:45');
        $this->assertEquals('2025-01-15 00:00:00', $result->format('Y-m-d H:i:s'));
    }

    public function testEndOfDay(): void
    {
        $result = DateHelper::endOfDay('2025-01-15 10:30:00');
        $this->assertEquals('2025-01-15 23:59:59', $result->format('Y-m-d H:i:s'));
    }

    public function testParseImmutable(): void
    {
        $result = DateHelper::parseImmutable('2025-01-15');
        $this->assertInstanceOf(\Carbon\CarbonImmutable::class, $result);
        $this->assertEquals('2025-01-15', $result->format('Y-m-d'));
    }
}
// End of AI-generated code
