<?php

/**
 * DateHelper - Utility class for date operations using Carbon
 *
 * LICENSE: This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://opensource.org/licenses/gpl-license.php>;.
 *
 * @package OpenEMR
 * @author  GitHub Copilot AI Assistant
 * @link    http://www.open-emr.org
 */

namespace OpenEMR\Common\Utils;

// Generated by GitHub Copilot
use Carbon\Carbon;
use Carbon\CarbonImmutable;

class DateHelper
{
    /**
     * Parse a date string and return a Carbon instance
     *
     * @param string|int|null $date Date string, timestamp, or null for now
     * @param string|null $timezone Optional timezone
     * @return Carbon
     */
    public static function parse($date = null, ?string $timezone = null): Carbon
    {
        if ($date === null || $date === '') {
            return Carbon::now($timezone);
        }

        if (is_numeric($date)) {
            return Carbon::createFromTimestamp($date, $timezone);
        }

        return Carbon::parse($date, $timezone);
    }

    /**
     * Parse a date string and return a CarbonImmutable instance
     *
     * @param string|int|null $date Date string, timestamp, or null for now
     * @param string|null $timezone Optional timezone
     * @return CarbonImmutable
     */
    public static function parseImmutable($date = null, ?string $timezone = null): CarbonImmutable
    {
        if ($date === null || $date === '') {
            return CarbonImmutable::now($timezone);
        }

        if (is_numeric($date)) {
            return CarbonImmutable::createFromTimestamp($date, $timezone);
        }

        return CarbonImmutable::parse($date, $timezone);
    }

    /**
     * Format a date in Y-m-d format (SQL date format)
     *
     * @param string|int|null $date Date string, timestamp, or null for now
     * @return string
     */
    public static function formatToSqlDate($date = null): string
    {
        return self::parse($date)->format('Y-m-d');
    }

    /**
     * Format a date in Y-m-d H:i:s format (SQL datetime format)
     *
     * @param string|int|null $date Date string, timestamp, or null for now
     * @return string
     */
    public static function formatToSqlDateTime($date = null): string
    {
        return self::parse($date)->format('Y-m-d H:i:s');
    }

    /**
     * Add days to a date
     *
     * @param string|int $date Date string or timestamp
     * @param int $days Number of days to add (can be negative)
     * @return Carbon
     */
    public static function addDays($date, int $days): Carbon
    {
        return self::parse($date)->addDays($days);
    }

    /**
     * Add weeks to a date
     *
     * @param string|int $date Date string or timestamp
     * @param int $weeks Number of weeks to add (can be negative)
     * @return Carbon
     */
    public static function addWeeks($date, int $weeks): Carbon
    {
        return self::parse($date)->addWeeks($weeks);
    }

    /**
     * Add months to a date
     *
     * @param string|int $date Date string or timestamp
     * @param int $months Number of months to add (can be negative)
     * @return Carbon
     */
    public static function addMonths($date, int $months): Carbon
    {
        return self::parse($date)->addMonths($months);
    }

    /**
     * Subtract days from a date
     *
     * @param string|int $date Date string or timestamp
     * @param int $days Number of days to subtract
     * @return Carbon
     */
    public static function subDays($date, int $days): Carbon
    {
        return self::parse($date)->subDays($days);
    }

    /**
     * Subtract weeks from a date
     *
     * @param string|int $date Date string or timestamp
     * @param int $weeks Number of weeks to subtract
     * @return Carbon
     */
    public static function subWeeks($date, int $weeks): Carbon
    {
        return self::parse($date)->subWeeks($weeks);
    }

    /**
     * Subtract months from a date
     *
     * @param string|int $date Date string or timestamp
     * @param int $months Number of months to subtract
     * @return Carbon
     */
    public static function subMonths($date, int $months): Carbon
    {
        return self::parse($date)->subMonths($months);
    }

    /**
     * Get the difference in days between two dates
     *
     * @param string|int $date1 First date
     * @param string|int $date2 Second date
     * @param bool $absolute Return absolute value
     * @return int
     */
    public static function diffInDays($date1, $date2, bool $absolute = true): int
    {
        return self::parse($date1)->diffInDays(self::parse($date2), $absolute);
    }

    /**
     * Get the difference in hours between two dates
     *
     * @param string|int $date1 First date
     * @param string|int $date2 Second date
     * @param bool $absolute Return absolute value
     * @return int
     */
    public static function diffInHours($date1, $date2, bool $absolute = true): int
    {
        return self::parse($date1)->diffInHours(self::parse($date2), $absolute);
    }

    /**
     * Check if a date is in the past
     *
     * @param string|int $date Date to check
     * @return bool
     */
    public static function isPast($date): bool
    {
        return self::parse($date)->isPast();
    }

    /**
     * Check if a date is in the future
     *
     * @param string|int $date Date to check
     * @return bool
     */
    public static function isFuture($date): bool
    {
        return self::parse($date)->isFuture();
    }

    /**
     * Check if a date is today
     *
     * @param string|int $date Date to check
     * @return bool
     */
    public static function isToday($date): bool
    {
        return self::parse($date)->isToday();
    }

    /**
     * Get timestamp from a date
     *
     * @param string|int|null $date Date string or null for now
     * @return int
     */
    public static function toTimestamp($date = null): int
    {
        return self::parse($date)->timestamp;
    }

    /**
     * Check if first date is greater than second date
     *
     * @param string|int $date1 First date
     * @param string|int $date2 Second date
     * @return bool
     */
    public static function isGreaterThan($date1, $date2): bool
    {
        return self::parse($date1)->greaterThan(self::parse($date2));
    }

    /**
     * Check if first date is less than second date
     *
     * @param string|int $date1 First date
     * @param string|int $date2 Second date
     * @return bool
     */
    public static function isLessThan($date1, $date2): bool
    {
        return self::parse($date1)->lessThan(self::parse($date2));
    }

    /**
     * Check if two dates are the same day
     *
     * @param string|int $date1 First date
     * @param string|int $date2 Second date
     * @return bool
     */
    public static function isSameDay($date1, $date2): bool
    {
        return self::parse($date1)->isSameDay(self::parse($date2));
    }

    /**
     * Get start of day for a date
     *
     * @param string|int|null $date Date or null for today
     * @return Carbon
     */
    public static function startOfDay($date = null): Carbon
    {
        return self::parse($date)->startOfDay();
    }

    /**
     * Get end of day for a date
     *
     * @param string|int|null $date Date or null for today
     * @return Carbon
     */
    public static function endOfDay($date = null): Carbon
    {
        return self::parse($date)->endOfDay();
    }

    /**
     * Format date according to locale and pattern (replacement for dateformat())
     *
     * @param string|int|null $date Date to format
     * @param bool $withDayOfWeek Include day of week
     * @param string|null $locale Locale (defaults to session language)
     * @return string
     */
    public static function formatLocalized($date = null, bool $withDayOfWeek = false, ?string $locale = null): string
    {
        $carbon = self::parse($date);
        
        // Set locale from session if not provided
        if ($locale === null && isset($_SESSION['language_choice'])) {
            $languageTitle = getLanguageTitle($_SESSION['language_choice']);
            $locale = self::getLocaleFromLanguageTitle($languageTitle);
        }
        
        if ($locale) {
            $carbon->locale($locale);
        }

        // Format based on locale
        if ($withDayOfWeek) {
            return $carbon->translatedFormat('l, F j, Y');
        }
        
        return $carbon->translatedFormat('F j, Y');
    }

    /**
     * Convert OpenEMR language title to Carbon locale
     *
     * @param string $languageTitle Language title from getLanguageTitle()
     * @return string|null
     */
    private static function getLocaleFromLanguageTitle(string $languageTitle): ?string
    {
        $localeMap = [
            'English' => 'en',
            'Swedish' => 'sv',
            'Spanish' => 'es',
            'Spanish (Spain)' => 'es_ES',
            'Spanish (Latin American)' => 'es_LA',
            'German' => 'de',
            'Dutch' => 'nl',
            'Hebrew' => 'he',
        ];

        return $localeMap[$languageTitle] ?? 'en';
    }
}
// End of AI-generated code
