name: PHPStan

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

permissions:
  contents: read

jobs:
  phpstan:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: php-actions/composer@v6
      with:
        php_extensions: gd soap zip
    - uses: php-actions/phpstan@v3
      with:
        path: .
