name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # Single-element matrix provides named variable and job title
        node-version:
        - '22'
        php-version:
        - '8.4'
    services:
      mariadb:
        image: mariadb:11.8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
    - name: Get composer cache directory
      id: composer-cache
      run: |
        {
          printf 'dir='
          composer config cache-files-dir
        } >> "$GITHUB_OUTPUT"
    - name: Composer Cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-${{ matrix.php-version }}-
          ${{ runner.os }}-composer-
    - name: Composer Install
      run: composer install --prefer-dist --no-progress --optimize-autoloader --no-recommend
    - name: Save composer cache
      uses: actions/cache/save@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version}}
    - name: Get NPM Cache Directory
      id: npm-cache-dir
      run: |
        {
          printf 'dir='
          npm config get cache
        } >> "$GITHUB_OUTPUT"
    - name: Cache node modules
      # Use explicit restore and save actions to control
      # precisely when in the workflow the cache is
      # restored and saved.
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-
          ${{ runner.os }}-node-
    - name: NPM CI
      run: npm ci
    - name: CCDA NPM CI
      run: npm --prefix ccdaservice ci
    - name: Save node cache
      uses: actions/cache/save@v4
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
    - name: Run OpenEMR Auto Installer
      run: |
        php contrib/util/installScripts/InstallerAuto.php server=mariadb rootpass=root
      env:
        OPENEMR_ENABLE_INSTALLER_AUTO: "1"
    - name: Run OpenEMR Tests
      run: php -d memory_limit=8G vendor/bin/phpunit --testsuite=unit
